Calculate slot and manually set timestamp
lowprivuser/solana-test-framework pull request #1
Opened 2022-05-13 14:22 UTC by f44z

@lowprivuser could you do CR?

2022-05-13 18:41 UTC, lowprivuser requested changes
looks good, there's just one last little thing left to do

2022-05-13 18:41 UTC, lowprivuser commented on src/extensions/program_test_context.rs
> +            .checked_mul(1000000000) //convert from s to ns
would be nice to have a constant here

2022-05-14 06:11 UTC, f44z commented on src/extensions/program_test_context.rs
> +            .checked_mul(1000000000) //convert from s to ns
done

2022-05-14 18:35 UTC, lowprivuser approved these changes
Looks good, thanks!

2022-05-14 18:35 UTC, merged